r=int(input("Radius of Circle:"))
l=int(input("Length of Rectangle:"))
b=int(input("Breadth of Rectangle:"))
base=int(input("Base of Triangle:"))
h=int(input("Height of Triangle:"))
circle=3.14*r*r
rectangle=l*b
triangle=0.5*base*h
print("Area of circle=",circle)
print("Area of rectangle=",rectangle)
print("Area of triangle=",triangle)
